version: '3'
volumes:
  mysqldata:
    driver: "local"
services:
  db:
    #image: postgres:11
    container_name: mysql8
    build: "./app/mysql"
    command: 'mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      TZ: 'Asia/Tokyo'
    volumes:
      - "mysqldata:/var/lib/mysql"
      - "./res/mysql/my.cnf:/etc/mysql/mysql.conf.d"
      - "./init:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
